#host
@host = http://127.0.0.1:8080

#id
@idValid =  12
@idNotValid = -12
@idStr = adc_pro

#query
@query = name="Dwcks"&role=adc
@query_price = min=1&max=200

###
GET {{host}}
# route: /

###
GET {{host}}/static
# route: /static

###
GET {{host}}/api/{{idValid}}
# route: /:id

###
GET {{host}}/api/product
# route: /api/product

###
GET {{host}}/api/product/cate
# route: /api/product/cate/:id

###
GET {{host}}/api/product/2
# route: /api/product/:id

###
GET {{host}}/api/price?{{query_price}}
# route: /api/price

###
GET {{host}}/api/query?{{query}}
# route: /query

###
GET {{host}}/api/header
# route: /header
