#host
@host = http://127.0.0.1:8080

#id
@idValid =  12
@idNotValid = -12
@idStr = adc_pro

#query
@query = name="Dwcks"&role=adc

###
GET {{host}}
# route: /

###
GET {{host}}/{{idValid}}
# route: /:id

###
GET {{host}}/query?{{query}}
# route: /query

###
GET {{host}}/header
# route: /header
